### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Kynneb** [ESROCOS/tools-imagetransfer#1]
I seem to be unable to build this package correctly (on the build server or manually). The errors I get are printed below. I know those are enums defined in the dataview-uniq.h and should be included but perhaps there is a namespace-error I can't get around?

```
testproducer.c: In function 'testproducer_startup':
testproducer.c:24:24: error: 'asn1Sccmode_grayscale' undeclared (first use in this function)
     frame.frame_mode = asn1Sccmode_grayscale;
                        ^~~~~~~~~~~~~~~~~~~~~
testproducer.c:24:24: note: each undeclared identifier is reported only once for each function it appears in
testproducer.c:25:26: error: 'asn1Sccstatus_valid' undeclared (first use in this function)
     frame.frame_status = asn1Sccstatus_valid;

```

**Comment by RaquelJalvo** [comment]
Fixed! For problems related to types, you can assign the issues to me. Thank you for reviewing the installation.

**Comment by Kynneb** [comment]
I will try a new build immediatly :-)
Thanks for your response, I assigned the contributors but I will know for the future.

**Comment by Kynneb** [comment]
Now I got one error regarding the paths of type files (missing file base.asn) due to different $HOME paths on the development and testing machines respectively. This can be fixed by uncommenting line 3 ```
#./update_data_view.sh
```

in the user_init_pre.sh

**Comment by RaquelJalvo** [comment]
ups, you are right! Uncommented!

**Comment by Jomsanchez-gmv** [comment]
You should try to do `$ sh update_dataview.sh` in the model foldef to update the paths of the Dataview.aadl.
This file has all paths relatives to **$AUTOPROJ_CURRENT_ROOT** environment variable, so it should find base.asn without problems. Make sure you have all the packages needed previously installed.

**Comment by Kynneb** [comment]
Thanks, build running...

**Comment by Kynneb** [comment]
worked, thank you
